// Generated by CoffeeScript 1.3.3
(function() {
  var Collection, DB, Server;

  Server = require('mongolian');

  DB = require('mongolian/lib/db.js');

  Collection = require('mongolian/lib/collection.js');

  Server.prototype.db = function(name) {
    if (!(this._dbs[name] != null)) {
      this._dbs[name] = new DB(this, name);
      this._dbs[name].schema = new Collection(this._dbs[name], 'schemas');
    }
    return this._dbs[name];
  };

  DB.prototype.collection = function(name) {
    return this._collections[name] || (this._collections[name] = new Collection(this, name));
  };

  Collection.prototype.getSchema = function(callback) {
    var criteria;
    if (this.name === 'schemas') {
      throw 'MongoSum cannot get the schema of the schemas collection.';
    }
    criteria = {
      collection: this.name
    };
    return this.db.schema.find(criteria, function(err, schema) {
      if (schema == null) {
        schema = {};
      }
      return callback(err, schema);
    });
  };

  Collection.prototype._insert = Collection.prototype.insert;

  Collection.prototype.insert = function(object, callback) {
    return this._insert(object, function(err, data) {
      console.log('inserted');
      console.log('    ', err);
      console.log('    ', data);
      return callback.apply(this, arguments);
    });
  };

  module.exports = Server;

}).call(this);
