// Generated by CoffeeScript 1.3.3
(function() {
  var coll, db, dbms, mongo;

  mongo = require('./mongosum.js');

  dbms = new mongo;

  db = dbms.db('mongosum_test');

  coll = db.collection('test');

  coll.insert({
    a: 'george',
    b: 60
  });

}).call(this);
